# 这是只能外部访问的配置
version: '3'

services:
    sky-monitor-kafka:
        image: bitnami/kafka:latest
        container_name: sky-monitor-kafka
        ports:
            - '9092:9092'
            - '9093:9093'
        environment:
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@192.168.3.58:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.3.58:9092
            # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://sky-monitor-kafka:9092
            - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - ALLOW_PLAINTEXT_LISTENER=yes
        # volumes:
        #     - ./kafka_data:/bitnami/kafka/data

    sky-monitor-clickhouse:
        image: bitnami/clickhouse:latest
        container_name: sky-monitor-clickhouse
        ports:
            - '8123:8123' # HTTP interface
            - '9000:9000' # Native interface for clients
        environment:
            - CLICKHOUSE_USER=default
            - CLICKHOUSE_PASSWORD=skyClickhouse2024
            - CLICKHOUSE_DATABASE=default
        # volumes:
        #     - ./clickhouse_data:/bitnami/clickhouse

    sky-monitor-postgresql:
        image: bitnami/postgresql:latest
        container_name: sky-monitor-postgresql
        ports:
            - '5432:5432'
        environment:
            - POSTGRESQL_USERNAME=postgres
            - ALLOW_EMPTY_PASSWORD=yes
            - POSTGRESQL_DATABASE=postgres
        volumes:
            - ./postgresql_data:/bitnami/postgresql

    sky-monitor-redis:
        image: bitnami/redis:latest
        container_name: sky-monitor-redis
        ports:
            - '6379:6379'
        environment:
            - REDIS_PASSWORD=skyRedis2024
        # volumes:
        #     - ./redis_data:/bitnami/redis

networks:
    default:
        name: sky-monitor-kafka-clickhouse-network
        driver: bridge
# # 这是只能内部访问的配置
# version: '3'

# services:
#     sky-monitor-kafka:
#         image: bitnami/kafka:latest
#         container_name: sky-monitor-kafka
#         ports:
#             - '9092:9092'
#             - '9093:9093'
#         environment:
#             - KAFKA_CFG_PROCESS_ROLES=broker,controller
#             - KAFKA_CFG_NODE_ID=1
#             - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@sky-monitor-kafka:9093
#             - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://sky-monitor-kafka:9092,PLAINTEXT_HOST://localhost:9092
#             - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
#             - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#             - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#             - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#             - ALLOW_PLAINTEXT_LISTENER=yes
#         # volumes:
#         #   - ./kafka_data:/bitnami/kafka/data

#     sky-monitor-clickhouse:
#         image: bitnami/clickhouse:latest
#         container_name: sky-monitor-clickhouse
#         ports:
#             - '8123:8123' # HTTP interface
#             - '9000:9000' # Native interface for clients
#         environment:
#             - CLICKHOUSE_USER=default
#             - CLICKHOUSE_PASSWORD=skyClickhouse2024
#             - CLICKHOUSE_DATABASE=default
#         # volumes:
#         #   - ./clickhouse_data:/bitnami/clickhouse

#     sky-monitor-postgresql:
#         image: bitnami/postgresql:latest
#         container_name: sky-monitor-postgresql
#         ports:
#             - '5432:5432'
#         environment:
#             - POSTGRESQL_TIMEZONE=Asia/Shanghai # 数据库时区设置为上海时间
#             - POSTGRESQL_LOG_TIMEZONE=Asia/Shanghai # 日志时区设置为上海时间 # 设置时区为上海，这个非常重要，不然写入的时间相较于北京时间会少 8 小时
#             - POSTGRESQL_USERNAME=postgres
#             - ALLOW_EMPTY_PASSWORD=yes
#             - POSTGRESQL_DATABASE=postgres
#         volumes:
#             - ./postgresql_data:/bitnami/postgresql

#     sky-monitor-redis:
#         image: bitnami/redis:latest
#         container_name: sky-monitor-redis
#         ports:
#             - '6379:6379'
#         environment:
#             - REDIS_PASSWORD=skyRedis2024
#         # volumes:
#         #   - ./redis_data:/bitnami/redis

# networks:
#     default:
#         name: sky-monitor-network
#         driver: bridge
